# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagram_clone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for instagram_clone
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 6.3.0'

  target 'instagram_cloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'instagram_clone-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for instagram_clone-tvOS

  target 'instagram_clone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
